[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "agreetd"
user = "greetd"

# The initial session, which runs when the system boots.
[initial_session]
command = "Hyprland"
user = "root"
